version: '3.9'
services:
    dev:
        container_name: node-ts-boilerplate
        image: node:16
        volumes:
            - ../:/node-ts-boilerplate:shared
        working_dir: /node-ts-boilerplate
        ports:
            - 3000:3000
        # Overrides default command so things don't shut down after the process ends.
        command: /bin/sh -c "while sleep 1000; do :; done"
